
name: 'covid_19_tracking'
version: '1.0.0'
config-version: 2

profile: 'covid_19_tracking_dev'

# Paths
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

# Model config
models:
  covid_19_tracking:
      materialized: table

      cleansed:
          +schema: cleansed
          +labels:
              type: cleansed
          +partition_by:
              field: date
              data_type: date

      joined:
          +schema: joined
          +labels:
              type: joined
          +partition_by:
              field: date
              data_type: date

      presentation:
          +schema: presentation
          +labels:
              type: presentation
          +partition_by:
              field: date
              data_type: date
