version: 2

sources:
  - name: covid_sources
    tables:
      - name: usafacts_confirmed_cases
      - name: usafacts_deaths

  - name: mapping
    tables:
      - name: us_states_fips_codes
      - name: us_county_fips_codes
      - name: us_county_pop_2018_5yr_census
